dist: focal

language: elixir

env:
  global:
    - MIX_ENV=test

jobs:
  include:
    - elixir: "1.4"
      otp_release: "20.3.8.22"
      script: mix test
    - elixir: "1.5"
      otp_release: "20.3.8.22"
      script: mix test
    - elixir: "1.6"
      otp_release: "20.3.8.22"
      script: mix test
    - elixir: "1.7"
      otp_release: "22.0"
      script: mix test
    - elixir: "1.8"
      otp_release: "22.0"
      script: mix test
    - elixir: "1.9"
      otp_release: "22.0"
      script: mix test
    - elixir: "1.10"
      otp_release: "23.0"
      script: mix test
    - elixir: "1.11"
      otp_release: "23.0"
      script: mix test

notifications:
  email:
    recipients:
      - igasgeek@me.com
